pool:
  name: Azure Pipelines
  vmImage: ubuntu-22.04
trigger:
  - main
stages:
  - stage: spcbuild
    displayName: build spc packages
    jobs:
      - job: mavenjob
        displayName: spc package
        steps:
          - task: Maven@3
            displayName: spc package task
            inputs:
              mavenPOMFile: 'pom.xml'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
          - task: CopyFiles@2
            inputs:
              Contents: '**/target/spring-petclinic-3.0.0-SNAPSHOT.jar'
              TargetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: spc_artifact
